### ISSUE TITLE
Stagin and Production Url's

### ISSUE THREAD

**Issue by hrashdan** [devloopsnet/zain-cash#1]
from where can I have "Stagin Url" and "Production Url" ?

Thanks

**Comment by AbdullahFaqeir** [comment]
@hrashdan if you check the read me you'll find it as below 

`
deinfe('ZAIN_CASH_STAGIN_URL','<Stagin Url>');
deinfe('ZAIN_CASH_PRODUCTION_URL','<Production Url>');
`
